=== nfrolov/xml-coursework/music.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="music" type="MusicType" />

    <xs:simpleType name="CompilationIdentifierType">
        <xs:restriction base="xs:ID">
            <xs:pattern value="album\d+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="MediaType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="lp" />
            <xs:enumeration value="cd" />
            <xs:enumeration value="dvd" />
            <xs:enumeration value="usb" />
            <xs:enumeration value="hdd" />
            <xs:enumeration value="other" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="MusicType">
        <xs:sequence>
            <xs:element name="compilation" type="CompilationType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CompilationType">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="artist" type="xs:string" />
            <xs:element name="genre" type="xs:string" />
            <xs:element name="year" type="xs:gYear" />
            <xs:element name="format" type="xs:string" />
            <xs:element name="tracks" type="TrackListingType" />
            <xs:element name="purchased" type="PurchasedType" />
            <xs:element name="copies" type="CopyListingType" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="id" type="CompilationIdentifierType" />
        <xs:attribute name="media" type="MediaType" />
    </xs:complexType>

    <xs:complexType name="TrackListingType">
        <xs:sequence>
            <xs:element name="track" type="TrackType" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TrackType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="artist" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="PurchasedType">
        <xs:simpleContent>
            <xs:extension base="xs:date">
                <xs:attribute name="place" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="CopyListingType">
        <xs:sequence>
            <xs:element name="copy" type="CopyType" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CopyType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="date" use="required" type="xs:date" />
                <xs:attribute name="media" use="required" type="MediaType" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

</xs:schema>

=== nfrolov/xml-coursework/music.xml
<?xml version="1.0" encoding="utf-8" ?>
<music xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="music.xsd">
    <compilation id="album0001" media="cd">
        <name>A Day Without Rain</name>
        <artist>Enya</artist>
        <genre>New Age</genre>
        <year>2000</year>
        <format>pcm</format>
        <tracks>
            <track>A Day Without Rain</track>
            <track>Wild Child</track>
            <track>Only Time</track>
            <track>Tempus Vernum</track>
            <track>Deora Ar Mo Chroí</track>
            <track>Flora's Secret</track>
            <track>Fallen Embers</track>
            <track>Silver Inches</track>
            <track>Pilgrim</track>
            <track>One By One</track>
            <track>The First Of Autumn</track>
            <track>Lazy Days</track>
        </tracks>
        <purchased place="Disc Shop">2010-01-25</purchased>
        <copies>
            <copy date="2011-01-25" media="hdd">Backup Storage</copy>
            <copy date="2012-01-25" media="hdd">Backup Storage</copy>
            <copy date="2013-01-25" media="hdd">Backup Storage</copy>
            <copy date="2013-05-05" media="other">Sony Walkman Player</copy>
        </copies>
    </compilation>
    <compilation id="album0002" media="cd">
        <name>A State of Trance 2011</name>
        <artist>VA</artist>
        <genre>Trance</genre>
        <year>2011</year>
        <format>pcm</format>
        <tracks>
            <track artist="Triple A">Winter Stayed (Armin van Buuren's On the Beach Intro Mix)</track>
            <track artist="The Blizzard &amp; Omnia">My Inner Island</track>
            <track artist="Mike Shiver vs Matias Lehtola">Slacker</track>
            <track artist="Dreas vs Alex Robert">Mormugao (Alex Robert 2011 Mix)</track>
            <track artist="Anhken">Always Look Back</track>
            <track artist="Nuera">Green Cape Sunset</track>
            <track artist="Rex Mundi">Sandstone</track>
            <track artist="Robert Nickson &amp; Thomas Datt">Godless (Protoculture Remix)</track>
            <track artist="Bobina">Lamento Sentimental</track>
            <track artist="Mark Otten">Libertine</track>
            <track artist="Max Graham feat. Neev Kennedy">So Caught Up</track>
            <track artist="Ashley Wallbridge">Moonlight Sonata</track>
            <track artist="Beat Service feat. Cathy Burton">When Tomorrow Never Comes</track>
            <track artist="Arty &amp; Mat Zo">Rebound</track>
        </tracks>
        <purchased place="Internet Disc Shop">2011-02-17</purchased>
        <copies>
            <copy date="2012-02-17" media="hdd">Backup Storage</copy>
            <copy date="2013-02-17" media="hdd">Backup Storage</copy>
        </copies>
    </compilation>
    <compilation id="album0003" media="cd">
        <name>Amarantine</name>
        <artist>Enya</artist>
        <genre>New Age</genre>
        <year>2005</year>
        <format>pcm</format>
        <tracks>
            <track>Less than a pearl</track>
            <track>Amarantine</track>
            <track>It's in the rain</track>
            <track>If I could be where you are</track>
            <track>The river sings</track>
            <track>Long long journey</track>
            <track>Sumiregusa</track>
            <track>Someone said goodbye</track>
            <track>A moment lost</track>
            <track>Drifting</track>
            <track>Amid the falling snow</track>
            <track>Water shows the hidden heart</track>
        </tracks>
        <purchased place="Auction">2012-03-13</purchased>
    </compilation>
    <compilation id="album0004" media="cd">
        <name>Voyageur</name>
        <artist>Enigma</artist>
        <genre>New Age</genre>
        <year>2003</year>
        <format>pcm</format>
        <tracks>
            <track>From East to West</track>
            <track>Voyageur</track>
            <track>Incognito</track>
            <track>Page of Cups</track>
            <track>Boum</track>
            <track>Total Eclipse of the Moon</track>
            <track>Look of Today</track>
            <track>In the Shadow, in the Light</track>
            <track>Weightless</track>
            <track>The Piano</track>
            <track>Following the Sun</track>
        </tracks>
        <purchased place="Friend">2013-03-19</purchased>
    </compilation>
    <compilation id="album0005" media="cd">
        <name>Magic Fields</name>
        <artist>X-Perience</artist>
        <genre>Synthie Pop</genre>
        <year>1996</year>
        <format>pcm</format>
        <tracks>
            <track>Deep Blue Water</track>
            <track>Magic Fields</track>
            <track>A Neverending Dream</track>
            <track>Mirror</track>
            <track>Beautiful Day</track>
            <track>Angel Zoom</track>
            <track>The Moon</track>
            <track>Circles Of Love (Radio Edit)</track>
            <track>The Night Moved On</track>
            <track>The Sun</track>
            <track>My Life Goes On</track>
            <track>Circles Of Love (D&amp;s Radio Mix)</track>
        </tracks>
        <purchased place="Internet Disc Shop">2005-08-13</purchased>
        <copies>
            <copy date="2011-08-13" media="cd">Backup copy</copy>
        </copies>
    </compilation>
    <compilation id="album0006" media="cd">
        <name>Chillaa</name>
        <artist>Robin</artist>
        <genre>Toilet</genre>
        <year>2012</year>
        <format>pcm</format>
        <tracks>
            <track>Chillaillaan</track>
            <track artist="Robin feat. Bräd">Puuttuva palanen</track>
            <track>Luupilla mun korvissa</track>
            <track>Biologiaa</track>
            <track>Biisi ystäville</track>
            <track>Kaunis luonnostaan</track>
            <track>Paniikkiin</track>
            <track>Häröilemään</track>
            <track>Sisko</track>
            <track>Haluun sun palaavan</track>
        </tracks>
        <purchased place="Found near a garbage can">2012-12-31</purchased>
        <copies>
            <copy date="2013-01-01" media="other">0 copies over torrent</copy>
        </copies>
    </compilation>
</music>
